name: PHP CS Fixer
on: pull_request
permissions:
  contents: read
jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run PHP CS Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --dry-run