name: PHP Unit
on: pull_request
permissions:
  contents: read

jobs:
  php-unit:
    name: PHP Unit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Validate Composer Files
      run: composer validate --strict
    - name: Cache Composer Packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Tests
      run: vendor/bin/phpunit tests/