name: Psalm
on: pull_request
permissions:
  contents: read
jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run Psalm
      uses: docker://ghcr.io/psalm/psalm-github-actions